"""Add deleted_at to games table

Revision ID: 11c86420e9b2
Revises: f6ab6727c3d3
Create Date: 2025-08-11 20:13:44.696074

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '11c86420e9b2'
down_revision: Union[str, Sequence[str], None] = 'f6ab6727c3d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('games', 'deleted_at')
    # ### end Alembic commands ###
