"""Add chat_id to Players and Games

Revision ID: 507e6cd9c87b
Revises: db486447d9ea
Create Date: 2025-07-11 22:29:30.816383

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '507e6cd9c87b'
down_revision: Union[str, Sequence[str], None] = 'db486447d9ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('chat_id', sa.Integer(), nullable=False))
    op.add_column('players', sa.Column('chat_id', sa.Integer(), nullable=False))
    op.create_unique_constraint('unique_player_per_group', 'players', ['telegram_id', 'chat_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_player_per_group', 'players', type_='unique')
    op.drop_column('players', 'chat_id')
    op.drop_column('games', 'chat_id')
    # ### end Alembic commands ###
