"""Add chat_id to Games

Revision ID: f6ab6727c3d3
Revises: db486447d9ea
Create Date: 2025-07-11 23:16:07.270960

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6ab6727c3d3'
down_revision: Union[str, Sequence[str], None] = 'db486447d9ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('chat_id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('games', 'chat_id')
    # ### end Alembic commands ###
