HELP_MESSAGE = (
    "<b>:book: How to Use the Game Manager Bot:</b>\n\n"
    "Each player <b>must</b> register using Add Me button before recording a game.\n\n"
    "<b>:video_game: To record a game:</b>\n"
    "<code>/played\n"
    "@winner1 @loser1\n"
    "@winner2 @loser2\n"
    ".\n"
    ".\n"
    ".\n"
    "[date=yyyy-mm-dd]</code>\n"
    "<i>Date is optional - defaults to today.</i>\n\n"
    "Example: <code>/played @alice @bob\n"
    "@charlie @dave\n"
    "date=2025-07-13</code>\n\n"
    "To see the games history, use\n<code>/games [date=yyyy-mm-dd]</code>.\n"
    "<i>Date is optional - defaults to today.</i>\n\n"
    "<b>:gear: See the Main Menu:</b> <code>/menu</code>\n\n"
    "<b>:trophy: To see the rankings:</b>\n"
    "Send <code>/rank</code> or use the Rankings button in the main menu.\n\n"
    "<b>:wastebasket: To delete a game:</b>\n"
    "Use the delete button in the success message after recording a game, "
    "or send <code>/delete_game &lt;id&gt;</code>.\n\n"
    "<b>:bust_in_silhouette: To register:</b>\n"
    "Use the Add Me button in the main menu or send <code>/add_me</code>."
    "\n\n"
    "<b>:man_technologist: Developer:</b> "
    "<a href='http://www.pouria.site/'>Pouria Forghani</a>"
)

START_MESSAGE = (
    ":wave: <b>Welcome to the Game Manager Bot!</b>\n\n"
    "Track your group's daily games, wins, and rankings — all "
    "automatically.\n\n"
    "Type /menu to see the menu.\n"
    "Type /help to learn how to use the bot."
)
